# R8 rules for the release build.
#
# Most of what Jejak uses already ships its own rules and needs nothing here:
#   - kotlinx.serialization  (kotlinx-serialization-core bundles R8 rules for @Serializable)
#   - Navigation Compose     (navigation-common bundles proguard.txt for type-safe routes)
#   - Hilt / Dagger          (the Hilt Gradle plugin contributes its own rules)
#
# The saved-session JSON format does not depend on these rules: the serializers generated by the
# kotlinx.serialization plugin embed property names as string literals, so renaming fields cannot
# change what is written to sessions.json.

# Readable stack traces in the Play Console. Upload the mapping file with the bundle.
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# osmdroid ships no consumer rules. It resolves tile sources, overlays and its configuration
# through reflection and XML-inflated views, so its own classes are kept whole.
-keep class org.osmdroid.** { *; }
-dontwarn org.osmdroid.**

# osmdroid pulls in optional SQLite/JSR-305 pieces that are absent at runtime.
-dontwarn org.slf4j.**
-dontwarn javax.annotation.**

# Retrofit/OkHttp are wired up in NetworkModule but no endpoint is called yet; these keep R8 quiet
# about the platform classes they reference optionally.
-dontwarn okhttp3.internal.platform.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
